main_app/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.home, name='home'),
    path('media/create', views.MediaCreate.as_view(), name='media_create'),
    path('media/', views.MediaList.as_view(), name='media_index'),
    path('media/<int:pk>', views.MediaDetail.as_view(), name='media_detail'),
    path('media/<int:media_id>/journal/create', views.JournalCreate.as_view(), name='journal_create'),
    path('journals/', views.journal_list, name='journals_index'),
    path('journals/<int:journal_id>', views.journal_detail, name='journals_detail'),
    path('journals/<int:pk>/update/', views.JournalUpdate.as_view(), name='journals_update'),
    path('journals/<int:pk>/delete/', views.JournalDelete.as_view(), name='journals_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('media/<int:media_id>/add_photo/', views.add_photo, name='add_photo')
]

streamerlemur/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

# Create your models here.

MPAA_RATINGS = (
    ('G', 'G'),
    ('P', 'PG'),
    ('1', 'PG-13'),
    ('R', 'R'),
    ('N', 'NC-17'),
    ('M', 'Mature Audience, Be Advised'),
    ('O', 'Not Rated')
)

YES_NO = (
    ('Y', "Yes"),
    ('N', 'No')
)

STREAMING = (
    ('N', 'Netflix'),
    ('A', 'Amazon Prime'),
    ('D', 'Disney'),
    ('F', 'Funimation'),
    ('H', 'Hulu'),
    ('B', 'HBO Max'),
    ('P', 'Peacock'),
    ('C', 'Crunchyroll'),
    ('M', 'Paramount+'),
    ('T', 'Apple TV+')
)
class Media(models.Model):
    name = models.CharField(max_length=350)
    description = models.TextField(max_length=650)
    action_genre = models.BooleanField()
    anime = models.BooleanField()
    cartoon = models.BooleanField()
    comedy = models.BooleanField()
    documentary = models.BooleanField()
    drama = models.BooleanField()
    family = models.BooleanField()
    fantasy = models.BooleanField()
    horror = models.BooleanField()
    mystery = models.BooleanField()
    romance = models.BooleanField()
    scifi = models.BooleanField()
    thriller = models.BooleanField()
    mpaa_rating = models.CharField(
        max_length=1,
        choices=MPAA_RATINGS,
        default=MPAA_RATINGS[0][0]
     )
    
    netflix = models.BooleanField()
    amazon_prime = models.BooleanField()
    disney_plus = models.BooleanField()
    funimation = models.BooleanField()
    hulu = models.BooleanField()
    hbo_max = models.BooleanField()
    peacock = models.BooleanField()
    crunchyroll = models.BooleanField()
    paramount_plus = models.BooleanField()
    apple_tv_plus = models.BooleanField()
    movie = models.CharField(
        max_length=1,
        choices=YES_NO,
    )

    def get_absolute_url(self):
        return reverse('media_detail', kwargs={'pk': self.id})





class Journal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    # media = models.
    where_am_i_watching = models.CharField(
        max_length=1,
        choices=STREAMING,
        default=STREAMING[0][0]
    )
    last_date_watched = models.DateField()
    last_episode_watched = models.CharField(
        max_length=100,
        default='N/A'
    )
    continue_watching = models.CharField(
        max_length=1,
        choices=YES_NO,
    )
    completed_watching = models.CharField(
        max_length=1,
        choices=YES_NO,
    )
    would_watch_again = models.CharField(
        max_length=1,
        choices=YES_NO,
    )
    def get_absolute_url(self):
        return reverse('journals_detail', kwargs={'journal_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length= 200)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for media_id: {self.media_id} @{self.url}'

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import Media, Journal, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

import uuid
import boto3


session = boto3.Session(profile_name='streamerlemur')
streamerlemur_s3_client = session.client('s3')

S3_BASE_URL = 'https://s3.us-west-2.amazonaws.com/'
BUCKET = 'streamerlemur'

def home(request):
    return render(request, 'home.html')


class MediaCreate(LoginRequiredMixin, CreateView):
    model = Media
    fields = '__all__'


class MediaList(ListView):
    model = Media


class MediaDetail(DetailView):
    model = Media
    


class JournalCreate(LoginRequiredMixin, CreateView):
    model = Journal
    fields = ['last_date_watched', 'continue_watching',
              'completed_watching', 'would_watch_again',
              'where_am_i_watching', 'last_episode_watched']

    def form_valid(self, form):
        media = Media.objects.get(id=self.kwargs['media_id'])
        form.instance.user = self.request.user
        form.instance.media = media
        return super().form_valid(form)


@login_required
def journal_list(request):
    journal_list = Journal.objects.filter(user=request.user)
    return render(request, 'main_app/journal_list.html', {'journal_list': journal_list})


@login_required
def journal_detail(request, journal_id):
    journal = Journal.objects.get(id=journal_id)
    media = Media.objects.get(id=journal.media.id)

    return render(request, 'main_app/journal_detail.html', {'journal': journal, 'media': media})


class JournalUpdate(LoginRequiredMixin, UpdateView):
    model = Journal
    fields = ['last_date_watched', 'continue_watching',
              'completed_watching', 'would_watch_again',
              'where_am_i_watching', 'last_episode_watched']


class JournalDelete(LoginRequiredMixin, DeleteView):
    model = Journal
    success_url = '/journals/'


def signup(request):
    error_message = 'this was so easy, how'
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'this was so easy, how'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


@login_required
def add_photo(request, media_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, media_id=media_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('media_detail', pk=media_id)

main_app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Streamer Lemur</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body style="background-color: rgb(41, 40, 40);"> 
    <header>
        <nav style= "background-color: rgb(93, 48, 226)" class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="{% static '/img/nav.png' %}" alt="LogoName" width=""
                  height="50"></a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- changes below -->
                        <li><a href="{% url 'media_index' %}">View All Media</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'media_create' %}">Add Media</a></li>
                        <li><a href="{% url 'journals_index' %}">View My Journals</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'logout' %}">Log Out</a></li>
                        {% else %}
                    </ul>
                        <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'login' %}">Log In</a></li>
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        {% endif %}  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}

        {% endblock %}
    </main>

</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
    <div class=" row">
        <div class=" mt-5  col-5 text-light">
            <h1 class="title">Streaming Made Easy</h1>
            <p class=" mx-5 p">Let Streamer Lemurs keep track of where you are watching your favorites.</p> 
        </div>
        <div class="col-7">
            <img class="logo" src="{% static '/img/homepage.png' %}" alt="Logo">
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/journal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Journal Now</h1>

<h4 class='text-light'>Are you sure you want to delete {{ object.media.name }}?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-dark">
    <a class='btn btn-dark' href="{% url 'journals_detail' journal.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/journal_detail.html
{% extends 'base.html' %}


{% block content %}
<h1>{{media.name}} </h1>
<div class='container'>
    <div class="row">
        <div class="card col col-3">
            <div class="card-content">
                <h6>Where am I streaming it?</h6>
                <p class="">{{journal.get_where_am_i_watching_display}}</p>
                <h6>When did I last watch this?</h6>
                <p>{{journal.last_date_watched}}</p>
                <h6>Do I want to continue watching this?</h6>
                <p>{{journal.get_continue_watching_display}}</p>
                <h6>Have I completed this?</h6>
                <p class="">{{journal.get_completed_watching_display}}</p>

                {% if journal.completed_watching == "Y" %}
                <h6>Would i Watch this again</h6>
                <p>{{journal.get_would_watch_again_display}}</p>
                {% endif %}
                {% if journal.movie == 'Y' %}
                <h6>This is a movie</h6>
                {% else %}

                <h6>This is a series</h6>
                {% endif %}


            </div>
        </div>
        <div class="mx-2 card col-8">
            <div class="card-content">
                <h6>Description:</h6>
                <p class="">{{media.description}}</p>
            </div>
        </div>
        <div class="card-action">
            <a class='btn btn-dark' href="{% url 'journals_update' journal.id %}">Edit</a>
            <a class='btn btn-dark' href="{% url 'journals_delete' journal.id %}">Delete</a>
        </div>
    </div>
</div>
<div class="row">
</div>


{% endblock content %}

main_app/templates/main_app/journal_form.html
{% extends 'base.html' %}


{% block content %}
{% if object %}
<h1 class='text-light'>Edit Journal</h1>
{% else %}
<h1 class='text-light'>Add Journal</h1>
{% endif %}
<form class= "form-group text-light" action='' method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value='Add to Journal' class="btn btn-dark">
</form>

{% endblock content %}

main_app/templates/main_app/journal_list.html
{% extends 'base.html' %}

{% block content %}

<div style="width: 55rem;" class="img_container">
    <h1>My Journals</h1>
    <h3 class='text-light'>Continue Watching</h3>
    <br>
    <div class="row gy-4 row-cols-4">
        {% for journal in journal_list %}
        {% if journal.continue_watching == 'Y' %}
        <a href="{% url 'journals_detail' journal.id %}">
            <div class="card col">
                <img src="{{journal.media.photo_set.first.url}}" class="card-img-top img-thumbnail"
                    style="height:17rem">
                <div class="card-body">
                    <p class="card-text">{{journal.media.name}}</p>
                </div>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    <br>
    <h3 class='text-light'>Watch Again</h3>
    <br>
    <div class="row gy-4 row-cols-4">
        {% for journal in journal_list %}
        {% if journal.completed_watching == 'Y' and journal.would_watch_again == 'Y' %}
        <a href="{% url 'journals_detail' journal.id %}">
            <div class="card col">
                <img src="{{journal.media.photo_set.first.url}}" class="card-img-top img-thumbnail"
                    style="height:17rem">
                <div class="card-body">
                    <p class="card-text">{{journal.media.name}}</p>
                </div>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    <br>
    <h3 class='text-light'>Have started but don't want to continue</h3>
    <br>
    <div class="row gy-4 row-cols-4">
        {% for journal in journal_list %}
        {% if journal.continue_watching == 'N' and journal.completed_watching == 'N' %}
        <a href="{% url 'journals_detail' journal.id %}">
            <div class="card col">
                <img src="{{journal.media.photo_set.first.url}}" class="card-img-top img-thumbnail"
                    style="height:17rem">
                <div class="card-body">
                    <p class="card-text">{{journal.media.name}}</p>
                </div>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    <br>
    <h3 class='text-light'>Don't want to watch again</h3>
    <br>
    <div class="row gy-4 row-cols-4">
        {% for journal in journal_list %}
        {% if journal.would_watch_again == 'N' and journal.continue_watching == 'N' and journal.completed_watching == 'Y' %}
        <a href="{% url 'journals_detail' journal.id %}">
            <div class="card col">
                <img src="{{journal.media.photo_set.first.url}}" class="card-img-top img-thumbnail" alt="..."
                    style="height:17rem">
                <div class="card-body">
                    <p class="card-text">{{journal.media.name}}</p>
                </div>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

main_app/templates/main_app/media_detail.html
{% extends 'base.html' %}


{% block content %}

<h1 class='text-light'>{{media.name}} </h1>
<div class='container'>
    <div class="row">
        <div class="card col-sm-12 col-md-3">
            <div class="card-content">
                <h6>Genre</h6>
                {% if media.action_genre %}
                <p>Action</p>
                {% endif %}
                {% if media.anime %}
                <p>Anime</p>
                {% endif %}
                {% if media.cartoon %}
                <p>Cartoon</p>
                {% endif %}
                {% if media.comedy %}
                <p>Comedy</p>
                {% endif %}
                {% if media.documentary %}
                <p>Documentary</p>
                {% endif %}
                {% if media.drama %}
                <p>Drama</p>
                {% endif %}
                {% if media.family %}
                <p>Family</p>
                {% endif %}
                {% if media.fantasy %}
                <p>Fantasy</p>
                {% endif %}
                {% if media.horror %}
                <p>Horror</p>
                {% endif %}
                {% if media.mystery %}
                <p>Mystery</p>
                {% endif %}
                {% if media.Romance %}
                <p>Romance</p>
                {% endif %}
                {% if media.scifi %}
                <p>Sci-fi</p>
                {% endif %}
                {% if media.thriller %}
                <p>Thriller</p>
                {% endif %}

                <h6>MPAA Rating:</h6>
                <p>{{media.get_mpaa_rating_display}}</p>

                <h6>Streaming: </h6>
                {% if media.netflix %}
                <p>Netflix</p>
                {% endif %}
                {% if media.amazon_prime %}
                <p>Amazon Prime</p>
                {% endif %}
                {% if media.disney_plus %}
                <p>Disney+</p>
                {% endif %}
                {% if media.funimation %}
                <p>Funimation</p>
                {% endif %}
                {% if media.hulu %}
                <p>Hulu</p>
                {% endif %}
                {% if media.hbo_max %}
                <p>HBO Max</p>
                {% endif %}
                {% if media.peacock %}
                <p>Peacock</p>
                {% endif %}
                {% if media.crunchyroll %}
                <p>Crunchyroll</p>
                {% endif %}
                {% if media.paramount_plus %}
                <p>Paramount+</p>
                {% endif %}
                {% if media.apple_tv_plus %}
                <p>Apple TV+</p>
                {% endif %}
            </div>
        </div>
        <div class="mx-1 card col-sm-12 col-md-6">
            <div class="card-content">
                <h6>Description:</h6>
                <p class="">{{media.description}}</p>
            </div>
        </div>
        <div class="col col-md-2">
            {% for photo in media.photo_set.all %}
            <img style='max-height:450px' src="{{photo.url}}">
            {% empty %}
            <div class="card-panel teal-text center-align">No Photos Uploaded</div>
            {% if user.is_authenticated %}
            <form action="{% url 'add_photo' media.id %}" enctype="multipart/form-data" method="POST" class="">
                {% csrf_token %}
                <input class='text-secondary' type="file" name="photo-file">
                <br><br>
                <input type="submit" class="btn btn-secondary" value="Upload Photo">
            </form>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="row">
    <a href="{% url 'journal_create' media.id %}" class="col-2 btn btn-dark">Create a Journal</a>
</div>




{% endblock content %}

main_app/templates/main_app/media_form.html
{% extends 'base.html' %}


{% block content %}

<h1 class="mx-auto text-light" style="width: 200px">Add Media</h1>
<div>
    <form class='form-group text-light' action='' method="POST">
        {% csrf_token %}
        <div class='row m-2'>
            <label for="name" class="col-sm-5 col-form-label">Movie or Series Name:</label>
            <div class="col-sm-12">
                <input type='text' maxlength="350" required name='name' class="form-control" id="name">
            </div>
        </div>
        <div class='row m-2'>
            <label for="description" class="col-5 col-form-label">Description:</label>
            <div class="col-12">
                <textarea class='form-control' maxlength='650' required name="description" id="description"
                    style='height:200px'></textarea>
            </div>
        </div>
        <div class='row m-2'>
            <label for="description" class="col-sm-3 col-form-label">Genre(s):</label>
            <div class="row check-class">
                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='action_genre' id="action_genre">
                    <label class="form-check-label" for="defaultCheck1">
                        Action
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='anime' id="anime">
                    <label class="form-check-label" for="defaultCheck1">
                        Anime
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='cartoon' id="cartoon">
                    <label class="form-check-label" for="defaultCheck1">
                        Cartoon/Animation
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='comedy' id="comedy">
                    <label class="form-check-label" for="defaultCheck1">
                        Comedy
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='documentary' id="documentary">
                    <label class="form-check-label" for="defaultCheck1">
                        Documentary
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='drama' id="drama">
                    <label class="form-check-label" for="defaultCheck1">
                        Drama
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='family' id="family">
                    <label class="form-check-label" for="defaultCheck1">
                        Family
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='fantasy' id="fantasy">
                    <label class="form-check-label" for="defaultCheck1">
                        Fantasy
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='horror' id="horror">
                    <label class="form-check-label" for="defaultCheck1">
                        Horror
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='mystery' id="mystery">
                    <label class="form-check-label" for="defaultCheck1">
                        Mystery
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='romance' id="romance">
                    <label class="form-check-label" for="defaultCheck1">
                        Romance
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='scifi' id="scifi">
                    <label class="form-check-label" for="defaultCheck1">
                        Sci-fi
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='thriller' id="thriller">
                    <label class="form-check-label" for="defaultCheck1">
                        Thriller
                    </label>
                </div>
            </div>
        </div>
        <div class='row m-2'>
            <label for="mpaa_rating" class="col- col-form-label">MPAA Rating:</label>
            <div class="col-12">
                <select required name="mpaa_rating" id="mpaa-rating">
                    <option value="G" selected>G</option>
                    <option value="P">PG</option>
                    <option value="1">PG13</option>
                    <option value="N">NC-17</option>
                    <option value="R">R</option>
                    <option value="M">Mature Audience, Be Advised</option>
                    <option value="O">Not Rated</option>
                </select>
            </div>
        </div>
        <div class='row m-2'>
            <label for="description" class="col-sm-3 col-form-label">Streaming:</label>
            <div class="row check-class">
                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='netflix' id="netflix">
                    <label class="form-check-label" for="defaultCheck1">
                        Netflix
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='amazon_prime' id="amazon_prime">
                    <label class="form-check-label" for="defaultCheck1">
                        Amazon Prime
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='disney_plus' id="disney_plus">
                    <label class="form-check-label" for="defaultCheck1">
                        Disney+
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='funimation' id="funimation">
                    <label class="form-check-label" for="defaultCheck1">
                        Funimation
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='hulu' id="hulu">
                    <label class="form-check-label" for="defaultCheck1">
                        Hulu
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='hbo_max' id="hbo_max">
                    <label class="form-check-label" for="defaultCheck1">
                        HBO Max
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='peacock' id="peacock">
                    <label class="form-check-label" for="defaultCheck1">
                        Peacock
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='crunchyroll' id="crunchyroll">
                    <label class="form-check-label" for="defaultCheck1">
                        Crunchyroll
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='paramount_plus' id="paramount_plus">
                    <label class="form-check-label" for="defaultCheck1">
                        Paramount+
                    </label>
                </div>

                <div class='col-3'>
                    <input class="form-check-input" type="checkbox" name='apple_tv_plus' id="apple_tv_plus">
                    <label class="form-check-label" for="defaultCheck1">
                        Apple TV+
                    </label>
                </div>
            </div>
        </div>
        <div class='row m-2'>
            <label for="id_movie" class="col- col-form-label">Movie or Series?</label>
            <div class="col-12">
                <select required name="movie" id="id_movie">
                    <option selected>-----</option>
                    <option value="Y">Movie</option>
                    <option value="N">Series or Other</option>
                </select>
            </div>
        </div>
        <input type='submit' button type="button" value='Submit' class="btn btn-dark"></input>
    </form>
</div>




{% endblock content %}

main_app/templates/main_app/media_list.html
{% extends 'base.html' %}


{% block content %}
<div style="width: 55rem;" class="img_container">
    <h1>All Media</h1>
    <div class="gy-4 row row-cols-4">
        {% for media in media_list %}
        <a href="{% url 'media_detail' media.id %}">
            <div class="card h-100 col ">
                <img src="{{media.photo_set.first.url}}" class="card-img-top img-thumbnail" style="height:17rem"
                    alt="...">
                <div class="card-body ">
                    <p style="color: rgb(81, 48, 226); text-align: center;" class="card-text">{{media.name}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}